{
    'name': "Sale Order Workflow",
    'summary': "Sale Order",
    'version': '10.0.1.0.0',
    'category': 'Sale',
    'company': "Akili Systems Pvt. Ltd.",
    'author': "Akili Systems Pvt. Ltd.",
    'website': "http://www.akilisystems.in/",
    'license': 'AGPL-3',
    'installable': True,
    'depends': ['sale', 'stock', 'product_team', 'sale_stock', 'pre_shipment', 'communication_type', 'website_sale','project_timesheet_holidays'],
    'data': [
        'security/ir.model.access.csv',
        'data/stock_data.xml',
        'wizard/assign_cart_to_quotation.xml',
        'wizard/approved_by_view.xml',
        'wizard/pay_view.xml',
        'views/assets.xml',
        'views/sale_cart_views.xml',
        'views/doc_seq.xml',
        'views/sale_view.xml',
        'views/sales_order_views.xml',
        'views/sale_quotation_views.xml',
        'views/stock_location_view.xml',
        'report/sale_report.xml',
    ],
}
