# -*- coding: utf-8 -*-
{
    'name': "Conservation Install Backend",
    'summary': """
        To install all dependent modules for Conservation Backend""", 
    'version': '10.0.1.0.0',
    'category': 'Uncategorized',
    'company': "Akili Systems Pvt. Ltd.",
    'author': "Akili Systems Pvt. Ltd.",
    'website': "http://www.akilisystems.in/",
    'license': 'Other proprietary',
    'installable': True,
    'application': True,
    'depends': [
    	'base_fontawesome',
    	'communication_type',
        'account_contacts',
        'account_desc',
        'account_logo',
        'account_sale_purchase_accounting',
        'mrp_custom',
        'so_workflow',
        'partner_address_type_default',
        'partner_credit_hold_credit_limit',
        'pre_shipment',
        'product_document',
        'product_extension',
        'product_team',
        'quotation_options_line',
        'sale_order_line_button',
        'list_view',
        'account_workflow',
        'authorize_net_payment_flow',
        'lead_process',
        'system_app',
        'backend_menuitem',
        'account_extra',
        'custom_chatter',
        'custom_pos',
        'l10n_us_account_profile',
        'om_account_accountant',
        'l10n_us_gaap_mis_report',
        'ak_dynamic_listview_backend'
        ],
    'data': [],
 }
